#!/bin/bash -e
: "${TARGET_PREFIX_DIR:?TARGET_PREFIX_DIR is not set}"

NDK_WRAPPER_DISABLED=1 $_CMAKE \
	-DBUILD_SHARED_LIBS=OFF \
	-DWEBP_BUILD_CWEBP=OFF \
	-DWEBP_BUILD_DWEBP=OFF \
	-DWEBP_BUILD_GIF2WEBP=OFF \
	-DWEBP_BUILD_IMG2WEBP=OFF \
	-DWEBP_BUILD_VWEBP=OFF \
	-DWEBP_BUILD_WEBPINFO=OFF \
	-DWEBP_BUILD_WEBPMUX=OFF \
	-DWEBP_BUILD_EXTRAS=OFF

$_NINJA
$_NINJA install
