#!/bin/bash -e

cp include/mbedtls/mbedtls_config.h{,.bak}

cat >>include/mbedtls/mbedtls_config.h <<"END"
#if defined(__aarch64__) || defined(__arm64__)
#define MBEDTLS_SHA256_USE_ARMV8_A_CRYPTO_ONLY
#define MBEDTLS_SHA512_USE_A64_CRYPTO_IF_PRESENT
#elif defined(__x86_64__) || defined(_M_X64)
#define MBEDTLS_HAVE_SSE2
#endif

#define MBEDTLS_AES_ROM_TABLES
#define MBEDTLS_GCM_LARGE_TABLE

#define MBEDTLS_SSL_VARIABLE_BUFFER_LENGTH

#define MBEDTLS_THREADING_C
#define MBEDTLS_THREADING_PTHREAD

// #define MBEDTLS_DEPRECATED_REMOVED

#undef MBEDTLS_CIPHER_MODE_CFB
#undef MBEDTLS_CIPHER_MODE_OFB
#undef MBEDTLS_CIPHER_MODE_XTS
#undef MBEDTLS_CIPHER_PADDING_ONE_AND_ZEROS
#undef MBEDTLS_CIPHER_PADDING_ZEROS_AND_LEN
#undef MBEDTLS_CIPHER_PADDING_ZEROS
#undef MBEDTLS_DES_C
#undef MBEDTLS_DHM_C
#undef MBEDTLS_ECP_DP_BP256R1_ENABLED
#undef MBEDTLS_ECP_DP_BP384R1_ENABLED
#undef MBEDTLS_ECP_DP_BP512R1_ENABLED
#undef MBEDTLS_ECP_DP_SECP192K1_ENABLED
#undef MBEDTLS_ECP_DP_SECP224K1_ENABLED
#undef MBEDTLS_ECJPAKE_C
#undef MBEDTLS_KEY_EXCHANGE_DHE_PSK_ENABLED
#undef MBEDTLS_KEY_EXCHANGE_DHE_RSA_ENABLED
#undef MBEDTLS_MD5_C
#undef MBEDTLS_PKCS12_C
#undef MBEDTLS_PKCS5_C
#undef MBEDTLS_PKCS7_C
#undef MBEDTLS_RIPEMD160_C
#undef MBEDTLS_SHA224_C
#undef MBEDTLS_SHA3_C
#undef MBEDTLS_SSL_SRV_C
#undef MBEDTLS_SSL_SESSION_TICKETS
#undef MBEDTLS_X509_CSR_PARSE_C
#undef MBEDTLS_X509_CSR_WRITE_C
END

$_CMAKE \
	-DENABLE_PROGRAMS=OFF \
	-DENABLE_TESTING=OFF

$_NINJA
DESTDIR="$prefix_dir" $_NINJA install

mv -f include/mbedtls/mbedtls_config.h{.bak,}